---
name: PR

# Controls when the action will run.
on:
  pull_request:
    types: [ labeled ]

jobs:
  test:
    name: test label
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'bug')
#    if: github.event.label.name == 'bug' || github.event.label.name == 'documentation'
    steps:
      - name: echo
        run: |
          echo -e "${{ github.event.label.name }}"
          echo -e "${{ join(github.event.pull_request.labels.*.name, ' | ') }}"
          echo -e "${{ github.event.pull_request.labels[0].name }}"
        shell: sh
