---
name: PR

# Controls when the action will run.
on: [ pull_request ]

jobs:
  test:
    name: test variable
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'bug')
    steps:
      - name: Dump context
        env:
#          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
          GITHUB_EVENT_LABEL: ${{ toJson(github.event.label) }}
#          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          # echo -e "GITHUB_EVENT_CONTEXT"
          echo -e "GITHUB_EVENT_LABEL"
          # echo -e "$GITHUB_CONTEXT"
        shell: sh
