---
name: PR

# Controls when the action will run.
on: [ pull_request ]

jobs:
  test:
    name: test variable
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo -e "$GITHUB_CONTEXT"
        shell: sh
