---
name: PR

# Controls when the action will run.
on: [ pull_request ]

jobs:
  test:
    name: test label
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'bug')
#    if: github.event.label.name == 'bug' || github.event.label.name == 'documentation'
    steps:
      - name: echo
        run: |
          echo "${{ join(github.event.pull_request.labels.*.name, ' | ') }}"
          echo "${{ toJson(github.event.pull_request.labels[0]) }}"
        shell: sh
