---
name: PR test

# Controls when the action will run.
on: [ pull_request ]

jobs:
  deploy:
    name: deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from repos
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/deploy
        with:
          MESSAGE: 'This is PR tests'

